version: '3.9'

services:
  database:
    container_name: EcommerceDB
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
      - 'upload_data:/home/zhj/uploads'
    restart: always
    env_file:
      - ./.env
    expose:
      - '5432'
    ports:
      - '55432:5432'
  api:
    container_name: EcommerceAPI
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py initial_admin && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - './ecommerce-api/:/usr/src/ecommerce-api/'
      - 'static_volume:/home/zhj/ecommerce/ecommerce-api/static'
      - 'media_volume:/home/zhj/ecommerce/ecommerce-api/media'
    expose:
      - '8000'
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    links:
      - 'database:database'
    depends_on:
      database:
        condition: service_started
  pgadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '8081:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=zuly.mhj@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=zU1y@Dm1n
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
      - 'upload_data:/home/zhj/uploads'
    links:
      - 'database:pgsql-server'
volumes:
  postgres_data:
  pgadmin_data:
  static_volume:
  upload_data:
  media_volume: