# Generated by Django 4.1.6 on 2023-02-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('logo', models.FileField(blank=True, null=True, upload_to='brand/logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('code', models.CharField(max_length=250, verbose_name='Code color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price unitity')),
                ('material', models.CharField(blank=True, max_length=250, null=True, verbose_name='Material')),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Unisex')], default=0, null=True, verbose_name='Type')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=4, null=True, verbose_name='Size')),
                ('has_sleeves', models.BooleanField(blank=True, null=True, verbose_name='has_sleeves')),
                ('stock_initial', models.IntegerField(default=0, verbose_name='Stock initial')),
                ('stock_now', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock now')),
                ('image', models.FileField(blank=True, null=True, upload_to='product/image', verbose_name='Image')),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Innactive'), (1, 'Active'), (2, 'Deleted')], default=0, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='catalog.brand', verbose_name='brand')),
                ('category', models.ForeignKey(help_text='Selected if is T-shirt o cap', on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='catalog.category', verbose_name='Category')),
                ('color_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color_brand', to='catalog.color', verbose_name='Color brand')),
                ('color_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_primary', to='catalog.color', verbose_name='Primary color')),
                ('color_secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_secondary', to='catalog.color', verbose_name='secondary color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
