# Generated by Django 3.2 on 2022-04-06 13:13
from django.db import transaction
from django.db import migrations
from django.utils.translation import gettext_lazy as _

product_data = [
    {
        "name": "Camiseta trébol con con estampado",
        "description": "Camiseta trébol con con estampado",
        "code": "PROD001",
        "price_unit": 25.99,
        "stock_initial": 20,
        "category_id": 1,
        "brand_id": 1,
        "color_primary_id": 1,
        "color_secondary_id": 1,
        "stock_now": 20,
        "type": 1,
        "material": "Algodón",
        "size": 'XS',
        "has_sleeves": True,
        "status": 1
    },
    {
        "name": "Camiseta unicolor de manga farol",
        "description": "Camiseta unicolor de manga farol",
        "code": "PROD002",
        "price_unit": 35.99,
        "stock_initial": 20,
        "category_id": 1,
        "brand_id": 2,
        "color_primary_id": 1,
        "color_secondary_id": 1,
        "stock_now": 20,
        "type": 1,
        "material": "Algodón",
        "size": 'XS',
        "has_sleeves": True,
        "status": 1
    },
    {
        "name": "Top corto con cordón delantero",
        "description": "Top corto con cordón delantero",
        "code": "PROD003",
        "price_unit": 25.99,
        "stock_initial": 20,
        "category_id": 1,
        "brand_id": 2,
        "color_primary_id": 1,
        "color_secondary_id": 1,
        "stock_now": 20,
        "type": 1,
        "material": "Algodón",
        "size": 'XS',
        "has_sleeves": False,
        "status": 1
    },
    {
        "name": "Top corto",
        "description": "Top corto",
        "code": "PROD004",
        "price_unit": 15.00,
        "stock_initial": 20,
        "category_id": 1,
        "brand_id": 1,
        "color_primary_id": 1,
        "color_secondary_id": 1,
        "stock_now": 20,
        "type": 1,
        "material": "Algodón",
        "size": 'XS',
        "has_sleeves": False,
        "status": 1
    },
    {
        "name": "Camiseta tejida de canalé de cuello de doblez",
        "description": "Camiseta tejida de canalé de cuello de doblez",
        "code": "PROD005",
        "price_unit": 35.99,
        "stock_initial": 20,
        "category_id": 1,
        "brand_id": 1,
        "color_primary_id": 1,
        "color_secondary_id": 1,
        "stock_now": 20,
        "type": 1,
        "material": "canalé",
        "size": 'XS',
        "has_sleeves": True,
        "status": 1
    },
    {
        "name": "Gorro con diseño de etiqueta",
        "description": "Gorro con diseño de etiqueta",
        "code": "PROD006",
        "price_unit": 20.00,
        "stock_initial": 10,
        "category_id": 1,
        "brand_id": 1,
        "color_brand_id": 1,
        "color_primary_id": 1,
        "color_secondary_id": 2,
        "stock_now": 10,
        "status": 1
    },
    {
        "name": "Gorro holgado con diseño de parche de letra con pañuelo infinito",
        "description": "Gorro holgado con diseño de parche de letra con pañuelo infinito",
        "code": "PROD007",
        "price_unit": 10.00,
        "stock_initial": 15,
        "category_id": 2,
        "brand_id": 3,
        "color_brand_id": 1,
        "color_primary_id": 1,
        "color_secondary_id": 2,
        "stock_now": 15,
        "status": 1
    },
    {
        "name": "Gorro béisbol unicolor minimalista",
        "description": "Gorro béisbol unicolor minimalista",
        "code": "PROD009",
        "price_unit": 30.00,
        "stock_initial": 10,
        "category_id": 2,
        "brand_id": 4,
        "color_brand_id": 1,
        "color_primary_id": 2,
        "color_secondary_id": 1,
        "stock_now": 10,
        "status": 1
    },
    {
        "name": "Gorra baker unicolor",
        "description": "Gorra baker unicolor",
        "code": "PROD006",
        "price_unit": 15.00,
        "stock_initial": 10,
        "category_id": 2,
        "brand_id": 1,
        "color_brand_id": 1,
        "color_primary_id": 2,
        "color_secondary_id": 1,
        "stock_now": 10,
        "status": 1
    },
    {
        "name": "Gorro con diseño de etiqueta",
        "description": "Gorro con diseño de etiqueta",
        "code": "PROD006",
        "price_unit": 20.00,
        "stock_initial": 10,
        "category_id": 2,
        "brand_id": 2,
        "color_brand_id": 1,
        "color_primary_id": 1,
        "color_secondary_id": 2,
        "stock_now": 10,
        "status": 1
    },
]


def insert_data(apps, schema_editor):
    product = apps.get_model('catalog', 'Product')
    for data in product_data:
        try:
            with transaction.atomic():
                product.objects.create(**data)
        except Exception as ex:
            print("error insert ---")
            print(ex)
            pass


def revert_insert_data(apps, schema_editor):
    product = apps.get_model('catalog', 'Product')
    for data in product_data:
        try:
            product.objects.filter(name=data['name']).delete()
        except:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_auto_migration_01022023'),
    ]

    operations = [
        migrations.RunPython(insert_data, revert_insert_data),
    ]
